version: '3'
services:
  textsavvyfront:
    image: textsavvyfront:latest
    environment:
      PORT: 3000
      PROXY_API: http://localhost:5000
    ports:
      - 3000:3000
  textsavvyback:
    image: textsavvyback:latest
    environment:
      MONGODB_URI: mongodb+srv://textSavvyUser:nerdyNomads4350@textsavvy.cgzhf.mongodb.net/textSavvyDB?retryWrites=true&w=majority
    ports:
      - 5000:5000