name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install dependencies
      working-directory: ./front-end
      run: npm install
  
    - name: Build
      working-directory: ./front-end
      run: npm run build