name: Release to Docker Hub

on:
  push:
    branches: [ implement-docker-image ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Backend
        run: echo "Building Backend..."
        run: ls
        run: docker build --file=backend.dockerfile  -t playground-web-backend .
        run: echo "Backend Build Complete!"

      - name: Build Frontend
        run: echo "Building Frontend..."
        run: docker build --file=front-end/frontend.dockerfile  -t playground-web-frontend .
        run: echo "Frontend Build Complete!"