name: Release to Docker Hub

on:
  milestone:
    types: closed
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Backend
        working-directory: ./
        run: docker build --file=back-end/backend.dockerfile -t playground-web-backend .

      - name: Build Frontend
        working-directory: ./
        run: docker build --file=front-end/frontend.dockerfile -t playground-web-frontend .