name: Release to Docker Hub

on:
  milestone:
    types: closed
  workflow_dispatch:

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}    

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
                
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          file_name: .env

      - name: Build using Docker compose
        working-directory: ./
        run: docker-compose build 
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - name: Push Backend
        working-directory: ./
        run: docker push vaaletee/text-savvy:db

      - name: Push Frontend
        working-directory: ./
        run: docker push vaaletee/text-savvy:web