name: Release to Docker Hub

on:
  push:
    branches: [ implement-docker-image ]
  workflow_dispatch:

jobs:

  Login-To-Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  Build-Backend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building Backend..."
      - run: docker build --file=./back-end/backend.dockerfile  -t playground-web-backend .
      - run: echo "Backend Build Complete!"

  Build-Frontend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building Frontend..."
      - run: docker build --file=front-end/frontend.dockerfile  -t playground-web-frontend .
      - run: echo "Frontend Build Complete!"